### ISSUE TITLE
Code of conduct update - Managing conflict 

### ISSUE THREAD

**Issue by will-s-205** [michaella23/bootcamp-collab#85]
ref: https://github.com/michaella23/bootcamp-collab/pull/82#pullrequestreview-1495457406

Manage conflict recommendations section could help in rare situations. Let's add some useful information about actions and steps in difficult situations like a conflict between community members.

**Comment by michaella23** [comment]
@will-s-205 thanks for creating this issue in reference to PR #82 review. For clarity, will you mention if you are going to work on the issues you create please? We don't have that many people going through these issues at this point, but this will be helpful if we do have more contributors, so that I don't assign it to someone else upon request. Thank you!

**Comment by will-s-205** [comment]
This issue is for conflict section update only. I consider it done due to the latest updates. If anyone else want to continue updating Code of Conduct then let's create a new issue. Closing out this one. Thank you for you consideration @michaella23
